Add logging and retry_constant
* Conditional logging functions based on BASH_LIB_LOG_LEVEL with
  appropriate colouring for each level.
* retry_constant function, similar to retry but with a retry_constant
  interval between attempts.

diff --git a/helpers/lib b/helpers/lib
--- a/helpers/lib
+++ b/helpers/lib
@@ -19,11 +19,16 @@ function spopd(){
     popd >/dev/null || die "popd failed :("
 }
 
+# Test if a variable contains a number
+function is_num(){
+    [[ ${1:-invalid} =~ ^-?[0-9\.]*$ ]]
+}
+
 # Retry a command multiple times until it succeeds, with escalating
 # delay between attempts.
 # Delay is 2 * n + random up to 30s, then 30s + random after that.
 # For large numbers of retries the max delay is effectively the retry
-# in minutes.
+# count in minutes.
 # Based on:
 # https://gist.github.com/sj26/88e1c6584397bb7c13bd11108a579746
 # but now quite heavily modified.
@@ -40,7 +45,7 @@ function retry {
     local retries=$1
     shift
 
-    if ! [[ ${retries} =~ ^[0-9\.]*$ ]]; then
+    if ! is_num "${retries}"; then
         echo "Invalid number of retries: ${retries} for command '${*}'".
         exit 1
     fi
@@ -64,6 +69,45 @@ function retry {
             wait=$(( backoff + (RANDOM % count) ))
             echo "'${*}' Retry $count/$retries exited $exit, retrying in $wait seconds..."
             sleep $wait
+        else
+            # Out of retries :(
+            echo "Retry $count/$retries exited $exit, no more retries left."
+            return $exit
+        fi
+    done
+    return 0
+}
+
+# retry function that waits a constant number of seconds between attempts.
+function retry_constant {
+    if [[ ${#} -lt 3 ]]; then
+        echo "retry usage: retry <retries> <interval (seconds)> <command>"
+        exit 1
+    fi
+
+    local retries=$1; shift
+    local interval=$1; shift
+
+    if ! is_num "${retries}"; then
+        echo "Invalid number of retries: ${retries} for command '${*}'".
+        exit 1
+    fi
+
+    if ! is_num "${interval}"; then
+        echo "Invalid interval in seconds: ${retries} for command '${*}'".
+        exit 1
+    fi
+
+    local count=0
+    until eval "$@"; do
+        # Command failed, otherwise until would have skipped the loop
+
+        # Store return code so it can be reported to the user
+        exit=$?
+        count=$((count + 1))
+        if [ "${count}" -lt "${retries}" ]; then
+            echo "'${*}' Retry $count/$retries exited $exit, retrying in $interval seconds..."
+            sleep "${interval}"
         else
             # Out of retries :(
             echo "Retry $count/$retries exited $exit, no more retries left."
